version: '3'
services:
  node-app:
    build:
        context: .
        args:
          - NODE_ENV=production
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run start:prod

