version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - node-app
  node-app:
    build: .
    depends_on:
      - mongo
  
  mongo:
    image: mongo

  redis:
    image: redis
  
    

volumes:
  mongo-db:

